---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: environmentconfigs.apiextensions.crossplane.io
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
spec:
  group: apiextensions.crossplane.io
  names:
    kind: EnvironmentConfig
    listKind: EnvironmentConfigList
    plural: environmentconfigs
    singular: environmentconfig
    shortNames:
    - envcfg
    categories:
    - crossplane
  scope: Cluster
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: |
          An EnvironmentConfig contains user-defined unstructured values for
          use in a Composition.
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          data:
            type: object
            additionalProperties:
              x-kubernetes-preserve-unknown-fields: true
    subresources: {}
    additionalPrinterColumns:
    - name: AGE
      type: date
      jsonPath: .metadata.creationTimestamp
